<?php
session_start();
unset($_SESSION['user']);
unset($_SESSION['id']);
unset($_SESSION['fb_{YOUR_APP_ID}_code']);
unset($_SESSION['fb_{YOUR_APP_ID}_access_token']);
unset($_SESSION['fb_{YOUR_APP_ID}_user_id']);
header("Location:index.php");
exit;
?>